version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: superset_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: supersetpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - superset_network

  superset:
    image: apache/superset:latest
    container_name: superset_app
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_SECRET_KEY: your_secret_key
      SQLALCHEMY_DATABASE_URI: mysql://superset:supersetpassword@superset_mysql:3306/superset
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - superset_network
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -p 8088 -h 0.0.0.0"

volumes:
  mysql_data:
  superset_home:

networks:
  superset_network:
    driver: bridge
